### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by robertlynch3** [jamesb2147/netbox-status-loader#2]
I know this is hasn't been updated in a while, but I just found this script.

Getting an issue when I go to run it.

```
Traceback (most recent call last):
  File "ping_to_netbox.py", line 167, in <module>
    result = pool.map(threadedPingReverseSave, listOfIpsWithMask)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: do_one() takes exactly 3 arguments (2 given)
```

Thanks!

**Comment by jamesb2147** [comment]
Looks to me like you're using a different python-ping library. The one you'll need for this app is here: https://github.com/samuel/python-ping

I've not confirmed this via testing, but the error is saying that "do_one()" takes 3 arguments, and the code in samuel's python-ping clearly still shows 2 arguments... https://github.com/samuel/python-ping/blob/master/ping.py

**Comment by robertlynch3** [comment]
Appreciate the reply. I ended up reworking some of the code to take away the multithreading and it works for me. It's a little slow (400 IPs in about 5 minutes), but I only need it to run once a day. I also don't have it doing DNS search, not adding new IPs, and patching to the REST API instead of posting. 


This is an awesome tool!

```
#!/usr/bin/env python
#Copyright Sean Hunter
#Using MIT License (see license file for detail)

import json, requests, ipaddress, time
#Python3 way (currently broken)
#import ping3
#Python2 way (currently the only non-broken way)
import ping
from multiprocessing import Pool
from pprint import pprint

#############################################################################
#DEAR USER - YOU MUST DEFINE EVERYTHING FROM HERE ###########################
#############################################################################

#How long to wait for ping responses
timeout = 2
#Currently configured for a local run against a Docker Netbox install
#Adjust to fit your environment (in prod, probably on port 80 or 443)
ip_addresses_url = "http://localhost:8001/api/ipam/ip-addresses/"
ip_prefixes_url = "http://localhost:8001/api/ipam/prefixes/"

#Authorization header
#This must be generated from the Netbox web UI at http://netbox/user/api-tokens/
header={"Authorization": "Token "}

#Set to:
#1 - Scan RFC1918 space (192.168.0.0/16, 172.16.0.0/12, 10.0.0.0/8)
#2 - Scan IP addresses defined in Netbox
#3 - Scan prefixes defined in Netbox
load_scanner_from_rfc1918_or_netbox = 2


#############################################################################
#THROUGH HERE ###############################################################
#############################################################################

#NOTE: Current possible status for IP addresses in Netbox include:
#1 - Active
#2 - Reserved
#3 - Deprecated
#5 - DHCP
#Don't ask what happened to 4. I assume Jeremy Stretch murdered him, the poor fellow.

def threadedPingReverseSave(addr):
	#Drop trailing /xx
	ip = addr.split("/")[0]
	#Run ping twice - first to ensure ARP completes before second ping goes through
	#this is often visible in labs where the first ping to a newly online device will fail
	ping.do_one(ip, timeout, 1)
	ping.do_one(ip, timeout, 1)
	rtt = ping.do_one(ip, timeout, 1)
	#Create the appropriate search string for a PTR record by reversing the IP space and
	#adding in-addr.arpa to the query
	#If the ping failed...
	if rtt == None:
		print(ip + ": NO RESPONSE BEFORE ICMP TIMEOUT EXPIRY")
		#There's not a great answer here, so we're going to assume the IP is merely reserved
		#Feel free to adjust this to your needs
		status = 3
	#If the ping succeeded...
	else:
		print(ip + ": " +str(rtt))
		status = 1
	return status


if __name__ == '__main__':
	start_time = time.time()
	if load_scanner_from_rfc1918_or_netbox == 1:
		#Load from RFC1918
		print("Not currently loading addresses from RFC1918, even though I was told to!!")
	if load_scanner_from_rfc1918_or_netbox == 2:
		#GET IP addresses from Netbox
		print requests.get(ip_addresses_url+"?limit=5000", headers=header)
		response = requests.get(ip_addresses_url+"?limit=5000", headers=header)
		listOfIpsWithMask = response.json()['results']
		for ipaddr in listOfIpsWithMask:
			ipaddr['isNew'] = "old"
	if load_scanner_from_rfc1918_or_netbox == 3:
		#GET IP prefixes from Netbox
		response = requests.get(ip_prefixes_url+"?limit=5000", headers=header)
		listOfPrefixes = response.json()['results']
		print(json.dumps(listOfPrefixes, indent=4))
		listOfIps = []
		for prefixObj in listOfPrefixes:
			print(prefixObj['prefix'])
			print(ipaddress.ip_network(prefixObj['prefix']).hosts())
			for host in ipaddress.ip_network(prefixObj['prefix']).hosts():
				listOfIps.append({"address": str(host)})
		listOfIpsWithMask = listOfIps
		for ipaddr in listOfIpsWithMask:
			ipaddr['isNew'] = "new"

	index=0
	for i in listOfIpsWithMask:
		if listOfIpsWithMask[index]['custom_fields']['Ignore from Automatic Status Update?']==True:
			index+=1
			continue
		else:
			if listOfIpsWithMask[index]['status']["value"]==1 or listOfIpsWithMask[index]['status']["value"]==3:
				newStatus=threadedPingReverseSave(listOfIpsWithMask[index]['address'])
				if newStatus!=listOfIpsWithMask[index]['status']["value"]:
					r=requests.request(method="patch",url=ip_addresses_url+str(listOfIpsWithMask[index]['id'])+"/", headers=header, json={"status": newStatus})
					print("\tREST API Status: "+str(r.status_code))
			index+=1


	#print(json.dumps(listOfIpsWithMask,indent=4))
	completion_time = time.time() - start_time
	minutes=int(completion_time / 60)
	seconds=int(completion_time % 60)
	print("Run took " + str(minutes) + " minutes and " + str(seconds) + " seconds")

```
